### ISSUE TITLE
Add Metis and Harmony Register contracts

### ISSUE THREAD

**Issue by githubdoramon** [appcalipse/meet-with-wallet-contracts#3]
Extend BaseRegister for Metis and Harmony.

Price feeds:
https://docs.chain.link/docs/harmony-price-feeds/
https://docs.diadata.org/documentation/oracle-documentation/deployed-contracts#metis

**Comment by yummyweb** [comment]
Extended BaseRegister for Harmony using chainlink. The contract is identical to Polygon.

**Comment by falleco** [comment]
test comment
